SERVER_PORT = 12000

SERVER_HOST = "localhost"

# NOTE: LEMBRAR DE VOLTAR PARA 1024 depois dos testes
MESSAGE_CHUNK_SIZE = 10

CLOSE_CLIENT_SOCKET_MESSAGE = "bye"

FINISH_SERVER_MESSAGE = "end_server"
