SERVER_PORT = 12000

SERVER_HOST = "localhost"

MESSAGE_CHUNK_SIZE = 1024

CLOSE_CLIENT_SOCKET_MESSAGE = "bye"

FINISH_SERVER_MESSAGE = "end_server"

GREETING_MESSAGE = "hi, meu nome eh "

USER_JOINED_THE_ROOM_MESSAGE = " entrou na sala!"

USER_CONNECTED_SUCCESSFULLY_MESSAGE = "Voce entrou no chat com sucesso, seja bem-vindo!"

USER_LEFT_THE_ROOM_MESSAGE = " saiu da sala!"

END_OF_MESSAGE_IDENTIFIER = "END_OF_MESSAGE_IDENTIFIER"

ACK_MESSAGE = "ACK"

NACK_MESSAGE = "NACK"
